# This workflow will generate an FBS and compare to data commons

name: Compare Single FBS

on:
  workflow_dispatch:      # manual trigger only
    inputs:
        method:
            description: "FBS"
            required: true
            default: "CAP_HAP_national_2017"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Update pip
      run: |
        python -VV
        python -m pip install --upgrade pip setuptools wheel

    # install package & dependencies
    - name: Install package and dependencies
      run: |
        pip install .

    - name: Generate FBS
      env:
          METHOD: ${{ github.event.inputs.method }}
      run: |
        echo "Method: ${{ github.event.inputs.method }}"
        python flowsa/test_single_FBS.py --method $METHOD

    - name: Upload files
      if: always()
      uses: actions/upload-artifact@v3
      with:
        # Artifact name
        name: FBS diff files
        # A file, directory or wildcard patter that describes what to upload
        path: | # uses local user data dir for ubuntu
          ~/.local/share/flowsa/FBSComparisons/*
          ~/.local/share/flowsa/FlowBySector/*
          ~/.local/share/stewi/Log/*
        if-no-files-found: warn # 'warn' or 'ignore' are also available, defaults to `warn`
        # retention-days: 5 # cannot exceed the retention limit set by the repository, organization, or enterprise.
