# This workflow will generate all FlowBySector files and store as artifact

name: Generate FBS

on:
  pull_request:
    branches: [master]
    types: [opened, reopened, ready_for_review]   # excludes syncronize to avoid redundant trigger from commits on PRs
  workflow_dispatch:            # also allow manual trigger, for testing purposes

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Update pip & install testing pkgs
      run: |
        python -VV
        python -m pip install --upgrade pip setuptools wheel
        pip install pytest

    # install package & dependencies
    - name: Install package and dependencies
      run: |
        pip install .

    - name: Generate FBS
      run: |
        pytest -m generate_fbs

    - name: Upload files
      if: always()
      uses: actions/upload-artifact@v3
      with:
        # Artifact name
        name: FlowBySector
        # A file, directory or wildcard patter that describes what to upload
        path: | # uses local user data dir for ubuntu
          ~/.local/share/flowsa/FlowBySector/*
          ~/.local/share/stewi/Log/*
        if-no-files-found: warn # 'warn' or 'ignore' are also available, defaults to `warn`
        # retention-days: 5 # cannot exceed the retention limit set by the repository, organization, or enterprise.
