# This workflow will install Python dependencies, run tests and lint
# across operating systems, select versions of Python, and user + dev environments
# For more info see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python CI/CD tests

on:
  push:
    # branches: [master, develop]
    paths-ignore:               # prevents workflow execution when only these types of files are modified
      - '**.md'                 # wildcards prevent file in any repo dir from trigering workflow
      - '**.bib'
      - '**.ya?ml'              # captures both .yml and .yaml
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    branches: [master, develop]
    types: [opened, reopened]   # excludes syncronize to avoid redundant trigger from commits on PRs
    paths-ignore:
      - '**.md'
      - '**.bib'
      - '**.ya?ml'
      - 'LICENSE'
      - '.gitignore'
  workflow_dispatch:            # also allow manual trigger, for testing purposes

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        py-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3

    # general Python setup
    - name: Set up Python ${{ matrix.py-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.py-version }}

    - name: Update pip & install testing pkgs
      run: |
        python -VV
        python -m pip install --upgrade pip setuptools wheel
        pip install pytest pytest-cov flake8

    # install package & dependencies
    - name: Install package and dependencies
      env:
        # Temporary fix to avoid git lfs error in fedelemflowlist install https://github.com/git-lfs/git-lfs/issues/5749
        GIT_CLONE_PROTECTION_ACTIVE: false
      run: |
        pip install .

    # linting & pytest
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test with pytest
      run: |
        pytest --doctest-modules -m "not generate_fbs"

  FBS_method_testing:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Update pip & install testing pkgs
      run: |
        python -VV
        python -m pip install --upgrade pip setuptools wheel
        pip install pytest pytest-cov flake8

    # install package & dependencies
    - name: Install package and dependencies
      env:
        # Temporary fix to avoid git lfs error in fedelemflowlist install https://github.com/git-lfs/git-lfs/issues/5749
        GIT_CLONE_PROTECTION_ACTIVE: false
      run: |
        pip install .

    - name: Test FBS config
      run: |
        python tests/test_FBS_methods.py
